services:
  - name: fo-trading-backend
    type: web
    env: node
    build:
      command: cd server && npm install
    start:
      command: cd server && npm start
    env_vars:
      NODE_ENV: production
      PORT: 5000
      YAHOO_FINANCE_KEY: ${{YAHOO_FINANCE_KEY}}
      ALPHA_VANTAGE_KEY: ${{ALPHA_VANTAGE_KEY}}
    health_check_path: /api/health
    
  - name: fo-trading-frontend
    type: static_site
    build:
      command: npm install && npm run build
    static_publish_path: ./build
    env_vars:
      NODE_ENV: production
      REACT_APP_API_URL: https://fo-trading-backend.onrender.com