services:
  - name: fo-trading-frontend
    type: static_site
    build:
      command: npm install && npm run build
    static_publish_path: ./build
    env_vars:
      NODE_ENV: production
      REACT_APP_API_URL: https://fo-trading-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html